### ISSUE TITLE
NGINX 在Ubuntu 16.04 和17.10上无法启动

### ISSUE THREAD

**Issue by ALESONICFICTIOZ** [wulabing/V2Ray_ws-tls_bash_onekey#24]
作者你好！上次出现的这个问题今天安装时候又出现了，看来是脚本新版本的问题？^_^ Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details. （系统为Ubuntu 16.04 和 17.10)

**Comment by ALESONICFICTIOZ** [comment]
我一共安装过两次，都是先重装系统，再安装脚本，同一台机器，新系统打开直接安装脚本，会提示这样的一行英文“Job for nginx.s..................................”

至于“在已经安装nginx的系统上多次执行脚本会导致nginx.conf配置出现问题” 这样的情况，我倒不知道，没试过.....

**Comment by wulabing** [comment]
明白了，我知道问题在什么地方。等一下更新，感谢反馈

**Comment by ALESONICFICTIOZ** [comment]
我记得上上版本出现了这个问题，然后你修复了....于是上一个版本安装一切正常，然后这个版本又出现了同样的问题.......^_^ 

谢谢作者，辛苦啦！！

**Comment by wulabing** [comment]
进行了一下简单的修复（还请麻烦反馈一下结果），同时还发现了一个新的问题，不过不影响使用，会在稍后阶段统一修复

**Comment by ALESONICFICTIOZ** [comment]
我今天debian 9 和ubuntu 16，17一共安装了3次，证书签发次数好像用完了（我记得是一周三次还是一天三次来着...），然后debian 9安装成没成功我给忘了...所以就没往标题里写，明天我再试试。

**Comment by wulabing** [comment]
辛苦了，我会在闲暇时间先自己进行一下测试，同时修复一下其他的问题

**Comment by ALESONICFICTIOZ** [comment]
没事...我经常爱瞎折腾...每个新版本出了都安装试试

**Comment by wulabing** [comment]
已放出较为完善的修复版本，目前等待测试结果

**Comment by ALESONICFICTIOZ** [comment]
Ubuntu 17.10 安装正常，可以使用了^_^

**Comment by wulabing** [comment]
感谢反馈

**Comment by laoz77** [comment]
我也出现了不能启动nginx的问题，运行systemctl status nginx.service得到的结果如下：
（我刚刚使用您最新的脚本进行了重新安装就出现了这个问题）
# systemctl status nginx.service
● nginx.service - nginx - high performance web server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled)
   Active: failed (Result: exit-code) since Sat 2018-04-07 09:33:02 UTC; 30s ago
     Docs: http://nginx.org/en/docs/
  Process: 467 ExecStart=/usr/sbin/nginx -c /etc/nginx/nginx.conf (code=exited, status=1/FAILURE)

systemd[1]: Starting nginx - high performance web server...
nginx[467]: nginx: [emerg] "proxy_intercept_errors" directive is duplicate in /etc/nginx/nginx.conf:28
systemd[1]: nginx.service: control process exited, code=exited status=1
systemd[1]: Failed to start nginx - high performance web server.
systemd[1]: Unit nginx.service entered failed state.

**Comment by wulabing** [comment]
您好，由于之前脚本的一些缺陷， 如果您安装过3.13版本之前的脚本，你需要使用纯净的系统进行安装。在当前版本之后应该不再需要

**Comment by wulabing** [comment]
可以，会在后续更新中添加卸载方式
