### ISSUE TITLE
v2ray 5.x 版本出了，现在脚本默认启动不起来了

### ISSUE THREAD

**Issue by AntiMoron** [wulabing/V2Ray_ws-tls_bash_onekey#47]
FYI:

```
v2ray -config ${v2ray_config}
```
这个脚本不行了，要升级到

```
v2ray run ${v2ray_config}
```

**Comment by AntiMoron** [comment]
https://github.com/wulabing/V2Ray_ws-tls_bash_onekey/pull/48

**Comment by AntiMoron** [comment]
提交v2ray 5.0相关修改

**Comment by ilhuyi** [comment]
可以执行 systemctl status v2ray 看到脚本的路径是哪？

● systemctl start v2ray
Warning: v2ray.service changed on disk. Run 'systemctl daemon-reload' to reload units.
root@localhost:~# systemctl daemon-reload
root@localhost:~# systemctl start v2ray
root@localhost:~# systemctl restart v2ray
root@localhost:~#  systemctl status v2ray
● v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2022-09-08 01:09:09 CST; 34s ago

然后将etc/systemd/system/v2ray.service 文件中的
/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json
改成
/usr/bin/v2ray/v2ray run -config /etc/v2ray/config.json
加一个run即可 ，再命令行里执行一下
systemctl daemon-reload

**Comment by AntiMoron** [comment]
我已经这么干了、见引用issue

**Comment by AntiMoron** [comment]
已经merge了。closed
